### ISSUE TITLE
patchapp-frontend pod crashes

### ISSUE THREAD

**Issue by hzgraham** [hzgraham/patchapp#116]
```
---> Migrating database ...
LDAP URL and basedn: ldap.example.com dc=example,dc=com
This is the CACERT URL: http://ldap.example.com/ca.crt
Traceback (most recent call last):
  File "/opt/rh/python33/root/usr/lib64/python3.3/urllib/request.py", line 1248, in do_open
    h.request(req.get_method(), req.selector, req.data, headers)
  File "/opt/rh/python33/root/usr/lib64/python3.3/http/client.py", line 1061, in request
    self._send_request(method, url, body, headers)
  File "/opt/rh/python33/root/usr/lib64/python3.3/http/client.py", line 1099, in _send_request
    self.endheaders(body)
  File "/opt/rh/python33/root/usr/lib64/python3.3/http/client.py", line 1057, in endheaders
    self._send_output(message_body)
  File "/opt/rh/python33/root/usr/lib64/python3.3/http/client.py", line 902, in _send_output
    self.send(msg)
  File "/opt/rh/python33/root/usr/lib64/python3.3/http/client.py", line 840, in send
    self.connect()
  File "/opt/rh/python33/root/usr/lib64/python3.3/http/client.py", line 818, in connect
    self.timeout, self.source_address)
  File "/opt/rh/python33/root/usr/lib64/python3.3/socket.py", line 417, in create_connection
    for res in getaddrinfo(host, port, 0, SOCK_STREAM):
socket.gaierror: [Errno -2] Name or service not known
```

**Comment by hzgraham** [comment]
This error is due to the url being down, probably a try/except clause in the code will fix it

**Comment by hzgraham** [comment]
last commit fixed this issue
